export const FETCH_SENTENCE = 'FETCH_SENTENCE';
export const RECEIVE_SENTENCE = 'RECEIVE_SENTENCE';

export const FETCH_READER_LIST = 'FETCH_READER_LIST';
export const RECEIVE_READER_LIST = 'RECEIVE_READER_LIST';

export const FETCH_READER_DETAIL = 'FETCH_READER_DETAIL';
export const RECEIVE_READER_DETAIL = 'RECEIVE_READER_DETAIL';

export const FETCH_BOOK_CATEGORY_LIST = 'FETCH_BOOK_CATEGORY_LIST';
export const RECEIVE_BOOK_CATEGORY_LIST = 'RECEIVE_BOOK_CATEGORY_LIST';

export const FETCH_BOOK_LIST = 'FETCH_BOOK_LIST';
export const RECEIVE_BOOK_LIST = 'RECEIVE_BOOK_LIST';

export const FETCH_BOOK_DETAIL = 'FETCH_BOOK_DETAIL';
export const RECEIVE_BOOK_DETAIL = 'RECEIVE_BOOK_DETAIL';

export const FETCH_BOOK_CHAPTER_LIST = 'FETCH_BOOK_CHAPTER_LIST';
export const RECEIVE_BOOK_CHAPTER_LIST = 'RECEIVE_BOOK_CHAPTER_LIST';